# Generated by Django 4.0.1 on 2022-01-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Clientcontracts', to='crm.clients'),
        ),
        migrations.AlterField(
            model_name='events',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Clientevents', to='crm.clients'),
        ),
    ]
