# Generated by Django 4.0.1 on 2022-01-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracts',
            options={'verbose_name': 'Contrat'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Evènement'},
        ),
    ]
