# Generated by Django 4.0.1 on 2022-01-11 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0003_remove_contracts_event_events_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='compagny_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='sales_contact',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_sales': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='sales_contact',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_sales': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='attendees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='events',
            name='suport_contact',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_support': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Support', to=settings.AUTH_USER_MODEL),
        ),
    ]
