# Generated by Django 4.0.1 on 2022-01-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_clients_compagny_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='suport_contact',
            new_name='support_contact',
        ),
    ]
