# Generated by Django 4.0.1 on 2022-01-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=15, verbose_name='prenom')),
                ('last_name', models.CharField(max_length=15, verbose_name='nom')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_sales', models.BooleanField(default=False, verbose_name='sales team')),
                ('is_support', models.BooleanField(default=False, verbose_name='support team')),
                ('is_management', models.BooleanField(default=False, verbose_name='management team')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
